// Author: Roshaless | Email: Roshaless@outlook.com | Created by 2026.9.19
// <auto-generated/> not-auto-generated, just to block CA2255 warning [ModuleInitializer] ?

#nullable enable

using System.Collections.Concurrent;
using System.ComponentModel;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Windows;
using System.Windows.Input;
using System.Windows.Interop;
using System.Windows.Media;
using System.Windows.Threading;

namespace System.Windows
{
    file static class AutoInitializer
    {
        [ModuleInitializer]
        public static void Initialize()
        {
            Dispatcher.CurrentDispatcher.BeginInvoke(DispatcherPriority.ApplicationIdle, () =>
            {
                EventManager.RegisterClassHandler(
                    typeof(Window),
                    FrameworkElement.LoadedEvent,
                    new RoutedEventHandler(OnWindowLoaded));

                MouseHorizontalWheelHook.Initialize();
                OnWindowLoaded(Application.Current.MainWindow, EventArgs.Empty);
            });
        }

        private static void OnWindowLoaded(object sender, EventArgs e)
        {
            if (sender is Window window)
            {
                MouseHorizontalWheelHook.InitializeHook(window);
            }
        }
    }

    // WPF内部输入事件报告处理 & 推送到用户路由事件
    file partial class MouseHorizontalWheelHook
    {
        public static void Initialize()
        {
            // 确保只调用一次？
            //InputManager.Current.PreNotifyInput -= OnPreNotifyInput;
            //InputManager.Current.PostProcessInput -= OnPostProcessInput;

            InputManager.Current.PreNotifyInput += OnPreNotifyInput;
            InputManager.Current.PostProcessInput += OnPostProcessInput;
        }

        private static void OnPreNotifyInput(object sender, NotifyInputEventArgs e)
        {
            if (e.StagingItem.Input is { Handled: false, Device: MouseDevice, RoutedEvent.Name: "PreviewInputReport" } input)
            {
                var report = InputReportEventArgsStatic.GetReport(input);
                var actions = RawMouseInputReportStatic.GetActions(report);

                if ((Convert.ToInt32(actions) & 0x20000) == 0x20000)
                {
                    InputManangerStatic.SetMostRecentInputDevice(e.InputManager, input.Device);
                }
            }
        }

        private static void OnPostProcessInput(object sender, ProcessInputEventArgs e)
        {
            // PreviewMouseHorizontalWheel --> MouseHorizontalWheel
            if (e.StagingItem.Input.RoutedEvent == Mouse.PreviewMouseHorizontalWheelEvent)
            {
                if (e.StagingItem.Input is { Handled: false, Device: MouseDevice mouseDevice })
                {
                    MouseWheelEventArgs previewWheel = (MouseWheelEventArgs)e.StagingItem.Input;
                    MouseWheelEventArgs wheel = new(mouseDevice, previewWheel.Timestamp, previewWheel.Delta)
                    {
                        RoutedEvent = Mouse.MouseHorizontalWheelEvent
                    };

                    e.PushInput(wheel, e.StagingItem);
                }
            }

            if (e.StagingItem.Input.RoutedEvent.Name == "InputReport")
            {
                if (e.StagingItem.Input is { Handled: false, Device: MouseDevice mouseDevice } input)
                {
                    var report = InputReportEventArgsStatic.GetReport(input);
                    var actions = RawMouseInputReportStatic.GetActions(report);

                    var inputSource = MouseDeviceStatic.GetInputSource(mouseDevice);
                    if (inputSource != null && InputReportStatic.GetInputSource(report) == inputSource)
                    {
                        // Raw --> PreviewMouseHorizontalWheel
                        if ((Convert.ToInt32(actions) & 0x20000) == 0x20000)
                        {
                            MouseWheelEventArgs previewWheel = new(mouseDevice, InputReportStatic.GetTimestamp(report), RawMouseInputReportStatic.GetWheel(report))
                            {
                                RoutedEvent = Mouse.PreviewMouseHorizontalWheelEvent
                            };

                            e.PushInput(previewWheel, e.StagingItem);
                        }
                    }
                }
            }
        }
    }

    // 全局 Hook 注册 & 卸载管理
    file partial class MouseHorizontalWheelHook
    {
        private static readonly ConcurrentDictionary<PresentationSource, MouseHorizontalWheelHook> Hooks = [];

        public static void InitializeHook(Visual visual)
        {
            var source = (HwndSource)PresentationSource.FromVisual(visual);
            if (source is null || Hooks.ContainsKey(source)) return;

            Hooks.TryAdd(source, new MouseHorizontalWheelHook(source));
        }

        public static void UninitializeHook(HwndSource source)
        {
            if (source is not null && Hooks.TryRemove(source, out var hook))
            {
                hook.Dispose();
            }
        }
    }

    // WM 消息接收 & 水平滚动报告
    file partial class MouseHorizontalWheelHook : IDisposable
    {
        private readonly HwndSource Source;

        private MouseHorizontalWheelHook(HwndSource hwndSource)
        {
            Source = hwndSource;
            Source.AddHook(WndProc);
            Source.Disposed += OnDisposed;
        }

        public void Dispose()
        {
            Source.RemoveHook(WndProc);
            Source.Disposed -= OnDisposed;
        }

        private void OnDisposed(object? sender, EventArgs e)
        {
            UninitializeHook(Source);
        }

        // HorizontalWheelRotate = 0x20000
        private IntPtr WndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
        {
            if (msg == 0x020E /*WM_MOUSEHWHEEL*/)
            {
                // 方向似乎不对？取个反
                var wheel = -SignedHIWORD(wParam);
                int x = SignedLOWORD(lParam);
                int y = SignedHIWORD(lParam);

                var provider = HwndSourceStatic.GetMouse(Source);
                if (provider is not null)
                {
                    var pt = new System.Drawing.Point() { X = x, Y = y };
                    if (ScreenToClient(hwnd, ref pt))
                    {
                        handled = HwndMouseInputProviderStatic.ReportInput(provider, hwnd, default, 0x20000, pt.X, pt.Y, wheel);
                    }
                }
            }

            return IntPtr.Zero;
        }

        private static short SignedHIWORD(IntPtr ptr)
        {
            unchecked
            {
                if (Environment.Is64BitOperatingSystem)
                {
                    return (short)((ptr.ToInt64() >> 16) & 0xFFFF);
                }

                return (short)((ptr.ToInt32() >> 16) & 0xFFFF);
            }
        }

        private static short SignedLOWORD(IntPtr ptr)
        {
            unchecked
            {
                if (Environment.Is64BitOperatingSystem)
                {
                    return (short)(ptr.ToInt64() & 0xFFFF);
                }

                return (short)(ptr.ToInt32() & 0xFFFF);
            }
        }

        [DllImport("user32.dll", SetLastError = true)]
        [return: MarshalAs(UnmanagedType.Bool)]
        private static extern bool ScreenToClient(IntPtr hWnd, ref System.Drawing.Point lpPoint);
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public static class UIElementExtensions
    {
        private static readonly RoutedEvent UIElementPreviewMouseHorizontalWheelEvent;
        private static readonly RoutedEvent UIElementMouseWheelEvent;

        static UIElementExtensions()
        {
            UIElementPreviewMouseHorizontalWheelEvent = Mouse.PreviewMouseHorizontalWheelEvent.AddOwner(typeof(UIElement));
            UIElementMouseWheelEvent = Mouse.MouseHorizontalWheelEvent.AddOwner(typeof(UIElement));
        }

        extension(UIElement element)
        {
            public static RoutedEvent PreviewMouseHorizontalWheelEvent => UIElementPreviewMouseHorizontalWheelEvent;
            public static RoutedEvent MouseHorizontalWheelEvent => UIElementMouseWheelEvent;

            public void AddHandlerTyped<T>(RoutedEvent routedEvent, T handler, bool handledEventsToo) where T : Delegate
            {
                Delegate typed = handler;
                if (routedEvent.HandlerType.IsInstanceOfType(handler) is not true)
                {
                    typed = Delegate.CreateDelegate(routedEvent.HandlerType, handler.Target, handler.Method);
                }

                element.AddHandler(routedEvent, typed, handledEventsToo);
            }

            public void RemoveHandlerTyped<T>(RoutedEvent routedEvent, T handler) where T : Delegate
            {
                Delegate typed = handler;
                if (routedEvent.HandlerType.IsInstanceOfType(handler) is not true)
                {
                    typed = Delegate.CreateDelegate(routedEvent.HandlerType, handler.Target, handler.Method);
                }

                element.RemoveHandler(routedEvent, typed);
            }
        }
    }

    namespace Input
    {
        [EditorBrowsable(EditorBrowsableState.Never)]
        public static class MouseHorizontalWheelExtensions
        {
            private static readonly RoutedEvent BasePreviewMouseHorizontalWheelEvent;
            private static readonly RoutedEvent BaseMouseHorizontalWheelEvent;

            static MouseHorizontalWheelExtensions()
            {
                BasePreviewMouseHorizontalWheelEvent = EventManager.RegisterRoutedEvent("PreviewMouseHorizontalWheel", RoutingStrategy.Tunnel, typeof(MouseWheelEventArgs), typeof(Mouse));
                BaseMouseHorizontalWheelEvent = EventManager.RegisterRoutedEvent("MouseHorizontalWheel", RoutingStrategy.Bubble, typeof(MouseWheelEventHandler), typeof(Mouse));
            }

            extension(Mouse)
            {
                public static RoutedEvent PreviewMouseHorizontalWheelEvent => BasePreviewMouseHorizontalWheelEvent;
                public static RoutedEvent MouseHorizontalWheelEvent => BaseMouseHorizontalWheelEvent;
            }
        }
    }

    // ===================== 以下都是一坨 ==========================
    // {为了减少反射开销以及实现快速访问， 提前将相关调用通过表达式进行编译}
    // ===================== 以下都是一坨 ==========================
    file static class WPFAssemblies
    {
        public static readonly Assembly PresentationCoreAssembly = typeof(HwndSource).Assembly;
    }
    file static class InputManangerStatic
    {
        private static readonly Action<object, object> MostRecentInputDeviceSetter = ExpressionAccessor.BuildSetter(typeof(InputManager), "_mostRecentInputDevice");
        public static void SetMostRecentInputDevice(object instance, object value) => MostRecentInputDeviceSetter(instance, value);
    }
    file static class InputReportEventArgsStatic
    {
        private static readonly Type InputReportEventArgsType = WPFAssemblies.PresentationCoreAssembly.GetType("System.Windows.Input.InputReportEventArgs")!;
        private static readonly Func<object, object> ReportGetter = ExpressionAccessor.BuildGetter(InputReportEventArgsType, "Report");
        public static object GetReport(object instance) => ReportGetter(instance);
    }
    file static class InputReportStatic
    {
        private static readonly Type InputReportType = WPFAssemblies.PresentationCoreAssembly.GetType("System.Windows.Input.InputReport")!;
        private static readonly Func<object, PresentationSource> InputSourceGetter = ExpressionAccessor.BuildGetter<PresentationSource>(InputReportType, "InputSource");
        private static readonly Func<object, int> TimestampGetter = ExpressionAccessor.BuildGetter<int>(InputReportType, "Timestamp");
        public static PresentationSource GetInputSource(object instance) => InputSourceGetter(instance);
        public static int GetTimestamp(object instance) => TimestampGetter(instance);
    }
    file static class RawMouseInputReportStatic
    {
        private static readonly Type RawMouseInputReportType = WPFAssemblies.PresentationCoreAssembly.GetType("System.Windows.Input.RawMouseInputReport")!;
        private static readonly Func<object, object> ActionsGetter = ExpressionAccessor.BuildGetter(RawMouseInputReportType, "Actions");
        private static readonly Func<object, int> WheelGetter = ExpressionAccessor.BuildGetter<int>(RawMouseInputReportType, "Wheel");
        public static object GetActions(object instance) => ActionsGetter(instance);
        public static int GetWheel(object instance) => WheelGetter(instance);
    }
    file static class MouseDeviceStatic
    {
        private static readonly Func<object, object> InputSourceGetter = ExpressionAccessor.BuildGetter(typeof(MouseDevice), "_inputSource");
        public static object? GetInputSource(object instance)
        {
            var result = InputSourceGetter(instance);
            if (result is not null && result.GetType() != typeof(HwndSource))
            {
                return SecurityCriticalDataStatic.GetValue(result, typeof(PresentationSource));
            }

            return result;
        }
    }
    file static class HwndSourceStatic
    {
        private static readonly Type ProviderType = WPFAssemblies.PresentationCoreAssembly.GetType("System.Windows.Interop.HwndMouseInputProvider")!;
        private static readonly Func<object, object> MouseGetter = ExpressionAccessor.BuildGetter(typeof(HwndSource), "_mouse");
        public static object? GetMouse(object instance)
        {
            var result = MouseGetter(instance);
            if (result is not null && result.GetType() != ProviderType)
            {
                return SecurityCriticalDataStatic.GetValue(result, ProviderType);
            }

            return result;
        }
    }
    file static class HwndMouseInputProviderStatic
    {
        private static readonly Type RawMouseActionsType = WPFAssemblies.PresentationCoreAssembly.GetType("System.Windows.Input.RawMouseActions")!;
        private static readonly Type ProviderType = WPFAssemblies.PresentationCoreAssembly.GetType("System.Windows.Interop.HwndMouseInputProvider")!;
        private static readonly Func<object, int> MsgTimeGetter = ExpressionAccessor.BuildGetter<int>(ProviderType, "_msgTime");
        private static readonly Func<object, IntPtr, InputMode, int, object, int, int, int, bool> ReportInputMethod = BuildReportInput();

        public static bool ReportInput(object mouse, IntPtr hwnd, InputMode mode, object actions, int x, int y, int wheel)
        {
            return ReportInputMethod(mouse, hwnd, mode, MsgTimeGetter(mouse), actions, x, y, wheel);
        }

        private static Func<object, IntPtr, InputMode, int, object, int, int, int, bool> BuildReportInput()
        {
            var provider = System.Linq.Expressions.Expression.Parameter(typeof(object), "provider");
            var hwnd = System.Linq.Expressions.Expression.Parameter(typeof(IntPtr), "hwnd");
            var mode = System.Linq.Expressions.Expression.Parameter(typeof(InputMode), "mode");
            var timestamp = System.Linq.Expressions.Expression.Parameter(typeof(int), "timestamp");
            var actions = System.Linq.Expressions.Expression.Parameter(typeof(object), "actions");
            var x = System.Linq.Expressions.Expression.Parameter(typeof(int), "x");
            var y = System.Linq.Expressions.Expression.Parameter(typeof(int), "y");
            var wheel = System.Linq.Expressions.Expression.Parameter(typeof(int), "wheel");

            var typedProvider = System.Linq.Expressions.Expression.Convert(provider, ProviderType);
            var reportInputMethod = ProviderType.GetMethod("ReportInput", BindingFlags.Instance | BindingFlags.NonPublic)!;

            var call = System.Linq.Expressions.Expression.Call(
                typedProvider,
                reportInputMethod,
                hwnd,
                mode,
                timestamp,
                System.Linq.Expressions.Expression.Convert(actions, RawMouseActionsType),   // object → RawMouseActions
                x,
                y,
                wheel);

            return System.Linq.Expressions.Expression.Lambda<
                Func<object, IntPtr, InputMode, int, object, int, int, int, bool>>(
                call, provider, hwnd, mode, timestamp, actions, x, y, wheel).Compile();
        }
    }
    file static class SecurityCriticalDataStatic
    {
        private static readonly Dictionary<Type, Func<object, object>> TypedGetters = [];
        public static object GetValue(object instance, Type valueType)
        {
            if (TypedGetters.TryGetValue(valueType, out var getter) is not true)
            {
                TypedGetters.Add(valueType, getter = ExpressionAccessor.BuildGetter(instance.GetType(), "Value"));
            }

            return getter(instance);
        }
    }

    file static class ExpressionAccessor
    {
        public static Func<object, object> BuildGetter(Type declaringType, string member)
        {
            // obj => (object)obj.Property
            var obj = System.Linq.Expressions.Expression.Parameter(typeof(object), "obj");
            var cast = System.Linq.Expressions.Expression.Convert(obj, declaringType);
            var access = System.Linq.Expressions.Expression.PropertyOrField(cast, member);
            var boxed = System.Linq.Expressions.Expression.Convert(access, typeof(object));
            return System.Linq.Expressions.Expression.Lambda<Func<object, object>>(boxed, obj).Compile();
        }

        public static Func<object, TValue> BuildGetter<TValue>(Type declaringType, string member)
        {
            // obj => obj.Property
            var obj = System.Linq.Expressions.Expression.Parameter(typeof(object), "obj");
            var cast = System.Linq.Expressions.Expression.Convert(obj, declaringType);
            var access = System.Linq.Expressions.Expression.PropertyOrField(cast, member);
            return System.Linq.Expressions.Expression.Lambda<Func<object, TValue>>(access, obj).Compile();
        }

        public static Action<object, object> BuildSetter(Type declaringType, string propertyName)
        {
            // () => obj.PropertyOrField = value
            var obj = System.Linq.Expressions.Expression.Parameter(typeof(object), "obj");
            var value = System.Linq.Expressions.Expression.Parameter(typeof(object), "value");
            var cast = System.Linq.Expressions.Expression.Convert(obj, declaringType);
            var access = System.Linq.Expressions.Expression.PropertyOrField(cast, propertyName);
            var boxed = System.Linq.Expressions.Expression.Convert(value, access.Member is PropertyInfo p ? p.PropertyType : ((FieldInfo)access.Member).FieldType);
            var assign = System.Linq.Expressions.Expression.Assign(access, boxed);
            return System.Linq.Expressions.Expression.Lambda<Action<object, object>>(assign, obj, value).Compile();
        }
    }
}