<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net462;net8.0-windows;net10.0-windows</TargetFrameworks>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<LangVersion>preview</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>Zen.Scroll</RootNamespace>
	</PropertyGroup>
	
	<PropertyGroup>
		<Version>0.2.1</Version>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<RepositoryUrl>https://github.com/Roshaless/Zen.Scroll</RepositoryUrl>
		<PackageTags>wpf, scroll, animation, scrollviewer, xaml</PackageTags>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.400">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="PolySharp" Version="1.16.0" Condition="'$(TargetFramework)' == 'net462'">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	
	<ItemGroup>
		<None Include="..\LICENSE.txt">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
			<Visible>false</Visible>
		</None>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
			<Visible>false</Visible>
		</None>
	</ItemGroup>
</Project>
